### ISSUE TITLE
Problems with terraform plan

### ISSUE THREAD

**Issue by silviadpena** [oracle-quickstart/oci-arch-ci-cd#7] opened 2021-10-07 15:33 UTC
I've cloned the repo, created file terraform.tfvars and I get this message when I type terraform plan:
rror: Invalid index
│
│   on modules/jenkins-master/main.tf line 41, in resource "oci_core_instance" "TFJenkinsMaster":
│   41:     source_id               = data.oci_core_images.InstanceImageOCID.images[0].id
│     ├────────────────
│     │ data.oci_core_images.InstanceImageOCID.images is empty list of object
│

Any idea?
Thanks!

**Comment by lfeldman** [comment] 2021-12-02 10:54
@silviadpena I was not able to reproduce your issue. Could you please send more details on the content of your terraform.tfvars file? Could you please try the latest version of the code?

**Comment by lfeldman** [comment] 2021-12-06 16:21
There is no follow-up from @silviadpena. Closing the ticket.

**Closed by lfeldman** 2021-12-06 16:21 UTC
