### ISSUE TITLE
Executing with Resource Manager fails on sudo yum install -y xmlstarlet

### ISSUE THREAD

**Issue by frobertpixto** [oracle-quickstart/oci-arch-ci-cd#6] opened 2021-04-07 19:29 UTC
The setup.sh script fails with:  
```
sudo yum install -y xmlstarlet
module.jenkins-master.oci_core_instance.TFJenkinsMaster (remote-exec): Error: Nothing to do
```

Executing manually on a separate Oracle Linux 7.9 instance shows:
```
sudo yum install -y xmlstarlet
Loaded plugins: langpacks, ulninfo
No package xmlstarlet available.
Error: Nothing to do
```

To make it work, I had to change:
from:
`sudo yum install -y xmlstarlet`
to:
```
sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sleep 10
sudo yum install -y xmlstarlet
```

**Comment by lfeldman** [comment] 2021-12-02 11:03
@frobertpixto I am not able to reproduce the issue. Could you please try it again with the latest stack?

**Comment by frobertpixto** [comment] 2021-12-05 21:06
ok, I don't work on that anymore. You can close the issue. Thanks.

**Comment by lfeldman** [comment] 2021-12-06 06:57
Thanks for your response. Closing the issue.

**Closed** 2021-12-06 16:18 UTC
